apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
  name: grafana
  namespace: so1p2
spec:
  ports:
    - port: 3003
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP