apiVersion: v1
kind: Service
metadata:
  name: service-grpc
  namespace: so1p2
spec:
  type: ClusterIP
  ports:
  - name: grpc-client-port
    port: 3000
    targetPort: 3000
  - name: grpc-server-port
    port: 3001
    targetPort: 3001
  selector:
    role: route-grpc