apiVersion: v1
kind: Service
metadata:
  namespace: so1p2
  name: service-producer
spec:
  ports:
    - name: producer-port
      port: 3002
      targetPort: 3002
  selector:
    name: producer-deploy
  type: LoadBalancer