apiVersion: v1
kind: Service
metadata:
  name: service-rust
  namespace: so1p2
spec:
  type: ClusterIP
  ports:
  - name: rust-client-port
    port: 8000
    targetPort: 8000
  - name: rust-server-port
    port: 8080
    targetPort: 8080
  selector:
    role: route-rust