apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deploy
  namespace: so1p2
spec:
  selector:
    matchLabels:
      name: consumer-deploy
  replicas: 1
  template:
    metadata:
      labels:
        name: consumer-deploy
    spec:
      containers:
        - name: consumer
          image: bragiova/consumer:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: secret-consumer
                  key: PORT
            - name: KAFKABROKER
              valueFrom:
                secretKeyRef:
                  name: secret-consumer
                  key: KAFKABROKER
            - name: TOPIC
              valueFrom:
                secretKeyRef:
                  name: secret-consumer
                  key: TOPIC
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-consumer
                  key: REDIS_HOST
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-consumer
                  key: REDIS_PASS