apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-grpc
  namespace: so1p2
spec:
  selector:
    matchLabels:
      role: route-grpc
  replicas: 1
  template:
    metadata:
      labels:
        role: route-grpc

    spec:
      containers:
      - name: grpc-client
        image: bragiova/client_grpc
        ports:
        - containerPort: 3000
      - name: grpc-server
        image: bragiova/server_grpc
        ports:
        - containerPort: 3001
        env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: secret-grṕc-server
                key: PORT
          - name: PRODURL
            valueFrom:
              secretKeyRef:
                name: secret-grṕc-server
                key: PRODURL