apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: so1p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: secret-mongo